import { WorkerContractor, Contract, AcceptanceReport, PartyAInfo } from '../types';

export const DEFAULT_PARTY_A: PartyAInfo = {
  organizationName: 'CHI NHÁNH VẬN TẢI ĐƯỜNG SẮT NHA TRANG',
  address: '17 Thái Nguyên, Phường Nha Trang, Tỉnh Khánh Hòa',
  taxCode: '0110879376-008',
  representativeName: 'Ông Lê Quang Chính',
  representativeTitle: 'Giám đốc',
  phone: '0258.3822113',
};

export const INITIAL_WORKERS: WorkerContractor[] = [
  {
    id: 'w-01',
    fullName: 'Nguyễn Văn Hùng',
    birthDate: '1985-06-15',
    cccdNumber: '056085002134',
    cccdDate: '2021-08-10',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Số 42 đường Lê Thánh Tôn, Phường Lộc Thọ, TP. Nha Trang, Khánh Hòa',
    taxCode: '8342190871',
    phone: '0913.456.782',
    bankAccount: '1023847582',
    bankName: 'Vietcombank - CN Khánh Hòa',
    socialStatus: 'freelance',
    hasTaxCommitmentForm: true, // Bản cam kết thu nhập theo NĐ 253/2026/NĐ-CP (chưa đến mức nộp thuế)
    allocatedBudget: 50000000,
    notes: 'Nhận khoán xịt rửa vỏ ngoài toa xe và kính mặt ngoài các đoàn tàu SE, SNT tại Ga Nha Trang',
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'w-02',
    fullName: 'Trần Đình Dũng',
    birthDate: '1962-03-20',
    cccdNumber: '056062001988',
    cccdDate: '2022-04-15',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Thôn Phước Thạnh, Xã An Hải, Huyện Ninh Phước, Tỉnh Ninh Thuận (Khu vực Ga Tháp Chàm)',
    taxCode: '8092837411',
    phone: '0988.341.229',
    bankAccount: '6701000049281',
    bankName: 'BIDV - CN Ninh Thuận',
    socialStatus: 'retired',
    pensionBookNumber: '56982341 (Thẻ hưu trí BHXH Khánh Hòa cấp)',
    hasTaxCommitmentForm: true,
    allocatedBudget: 45000000,
    notes: 'Cán bộ hưu trí đường sắt, nhận khoán vệ sinh nội thất và ngoại thất toa xe tại Ga Tháp Chàm',
    createdAt: '2026-01-12T09:30:00Z',
  },
  {
    id: 'w-03',
    fullName: 'Lê Hoàng Nam',
    birthDate: '1991-11-04',
    cccdNumber: '056091004521',
    cccdDate: '2023-01-20',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Khu dân cư Diên An, Huyện Diên Khánh, Tỉnh Khánh Hòa',
    taxCode: '8529301948',
    phone: '0905.772.194',
    bankAccount: '050089234812',
    bankName: 'Sacombank - CN Nha Trang',
    socialStatus: 'dual_employer',
    primaryEmployerName: 'Công ty Cổ phần Kho bãi và Dịch vụ Vận tải Miền Trung',
    primaryLaborContractNo: 'HĐLĐ-MT/2023-088',
    primaryBhxhCode: '5621456988 (Đã nộp bản chụp VssID)',
    hasTaxCommitmentForm: false, // Có thu nhập từ 02 nơi trở lên -> bắt buộc khấu trừ 10% khi >= 5 triệu
    allocatedBudget: 65000000,
    notes: 'Lao động làm việc ngoài giờ bốc xếp, dỡ hàng hóa sang xe ô tô/kho hàng tại Ga Diên Khánh',
    createdAt: '2026-01-15T10:15:00Z',
  },
  {
    id: 'w-04',
    fullName: 'Hoàng Thị Mai',
    birthDate: '1988-09-12',
    cccdNumber: '056088007652',
    cccdDate: '2021-12-05',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Phường Ninh Hiệp, Thị xã Ninh Hòa, Tỉnh Khánh Hòa',
    taxCode: '8491823901',
    phone: '0935.118.990',
    bankAccount: '190348271029',
    bankName: 'Techcombank - CN Khánh Hòa',
    socialStatus: 'freelance',
    hasTaxCommitmentForm: false, // Chưa nộp cam kết thu nhập -> nếu >= 5tr khấu trừ 10%
    allocatedBudget: 40000000,
    notes: 'Nhận khoán dịch vụ vệ sinh, cọ rửa toa xe khách khu vực Ga Ninh Hòa',
    createdAt: '2026-02-01T08:45:00Z',
  },
  {
    id: 'w-05',
    fullName: 'Đặng Quốc Tuấn',
    birthDate: '1980-04-28',
    cccdNumber: '056080003215',
    cccdDate: '2022-09-18',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Thôn Phú Nông, Xã Vĩnh Ngọc, TP. Nha Trang, Khánh Hòa',
    taxCode: '8129038472',
    phone: '0918.665.230',
    bankAccount: '0061001094821',
    bankName: 'Vietcombank - CN Nha Trang',
    socialStatus: 'dual_employer',
    primaryEmployerName: 'Công ty TNHH Dịch vụ Cảng Biển Cam Ranh',
    primaryLaborContractNo: 'HĐ-CR/2022-41',
    primaryBhxhCode: '5619883421 (VssID hợp lệ)',
    hasTaxCommitmentForm: false, // 2 nơi thu nhập -> bắt buộc khấu trừ 10%
    allocatedBudget: 75000000,
    notes: 'Bốc dỡ hàng bao kiện và hàng rời ga bãi hàng Ga Nha Trang',
    createdAt: '2026-02-05T14:00:00Z',
  },
  {
    id: 'w-06',
    fullName: 'Phạm Văn Túc',
    birthDate: '1957-08-13',
    cccdNumber: '056057008129',
    cccdDate: '2021-05-10',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Số 112 đường Trần Quý Cáp, Phường Vạn Thắng, TP. Nha Trang, Khánh Hòa',
    taxCode: '8012948123',
    phone: '0903.551.842',
    bankAccount: '0061001199342',
    bankName: 'Vietcombank - CN Nha Trang',
    socialStatus: 'retired',
    pensionBookNumber: '5619570012 (Thẻ hưu trí đường sắt Khánh Hòa)',
    hasTaxCommitmentForm: true,
    allocatedBudget: 60000000,
    notes: 'Hợp đồng nguyên tắc bốc xếp hàng hóa tại bộ phận Hóa vận Ga Nha Trang theo nhu cầu thực tế',
    createdAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'w-07',
    fullName: 'Nguyễn Thành Long',
    birthDate: '1987-04-18',
    cccdNumber: '054087003412',
    cccdDate: '2022-03-10',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Đường Lê Trung Kiên, Phường 2, TP. Tuy Hòa, Tỉnh Phú Yên',
    taxCode: '8204918239',
    phone: '0914.882.319',
    bankAccount: '1014829103',
    bankName: 'Vietcombank - CN Phú Yên',
    socialStatus: 'freelance',
    hasTaxCommitmentForm: true,
    allocatedBudget: 55000000,
    notes: 'Nhận khoán dịch vụ vệ sinh và rửa vỏ toa xe tuyến tàu khách đón trả tại Trạm VTĐS Tuy Hòa',
    createdAt: '2026-02-15T08:30:00Z',
  },
  {
    id: 'w-08',
    fullName: 'Bùi Văn Phước',
    birthDate: '1982-11-25',
    cccdNumber: '052082006173',
    cccdDate: '2021-09-14',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Khu phố Diêu Trì, Thị trấn Diêu Trì, Huyện Tuy Phước, Tỉnh Bình Định',
    taxCode: '8193847291',
    phone: '0905.334.819',
    bankAccount: '5801000094821',
    bankName: 'BIDV - CN Bình Định',
    socialStatus: 'dual_employer',
    primaryEmployerName: 'Công ty Cổ phần Vận tải và Kho vận Quy Nhơn',
    primaryLaborContractNo: 'HĐLĐ-QN/2023-102',
    primaryBhxhCode: '5220829104 (Đã kiểm tra VssID)',
    hasTaxCommitmentForm: false,
    allocatedBudget: 70000000,
    notes: 'Bốc dỡ hàng hóa chuyển tải từ toa xe đường sắt sang ô tô tại bãi hàng Ga Diêu Trì',
    createdAt: '2026-02-20T09:00:00Z',
  },
];

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 'c-01',
    contractNumber: '01/2026/HĐGK-SP-NT',
    templateType: 'CLEANING_FREELANCE',
    workerId: 'w-01',
    partyA: DEFAULT_PARTY_A,
    stationLocation: 'Ga Nha Trang',
    signDate: '2026-01-10',
    signPlace: 'Chi nhánh Vận tải đường sắt Nha Trang',
    startDate: '2026-01-10',
    endDate: '2027-01-09',
    rateExteriorWash: 65000, // 65.000 đ/toa
    rateInteriorWash: 80000, // 80.000 đ/toa
    rateCargoPackage: 0,
    rateCargoBulk: 0,
    status: 'active',
    notes: 'Hợp đồng nguyên tắc vệ sinh rửa toa xe khách vãng lai 01 năm',
    createdAt: '2026-01-10T08:30:00Z',
  },
  {
    id: 'c-02',
    contractNumber: '02/2026/HĐGK-SP-NT',
    templateType: 'CLEANING_RETIRED',
    workerId: 'w-02',
    partyA: DEFAULT_PARTY_A,
    stationLocation: 'Ga Tháp Chàm',
    signDate: '2026-01-12',
    signPlace: 'Chi nhánh Vận tải đường sắt Nha Trang',
    startDate: '2026-01-12',
    endDate: '2027-01-11',
    rateExteriorWash: 65000,
    rateInteriorWash: 80000,
    rateCargoPackage: 45000,
    rateCargoBulk: 35000,
    status: 'active',
    notes: 'Giao khoán rửa toa xe đối với nhân sự đã hưởng chế độ hưu trí',
    createdAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'c-03',
    contractNumber: '03/2026/HĐGK-VTHN-NT',
    templateType: 'CARGO_DUAL_EMPLOYER',
    workerId: 'w-03',
    partyA: DEFAULT_PARTY_A,
    stationLocation: 'Ga Diên Khánh',
    signDate: '2026-01-15',
    signPlace: 'Chi nhánh Vận tải đường sắt Nha Trang',
    startDate: '2026-01-15',
    endDate: '2027-01-14',
    rateExteriorWash: 0,
    rateInteriorWash: 0,
    rateCargoPackage: 45000, // 45.000 đ/tấn
    rateCargoBulk: 35000,    // 35.000 đ/tấn
    status: 'active',
    notes: 'Khoán bốc xếp hàng hóa đường sắt sang ô tô/kho cho lao động ngoài giờ đã đóng BHXH đơn vị 1',
    createdAt: '2026-01-15T11:00:00Z',
  },
  {
    id: 'c-04',
    contractNumber: '04/2026/HĐGK-SP-NT',
    templateType: 'CLEANING_FREELANCE',
    workerId: 'w-04',
    partyA: DEFAULT_PARTY_A,
    stationLocation: 'Ga Ninh Hòa',
    signDate: '2026-02-01',
    signPlace: 'Chi nhánh Vận tải đường sắt Nha Trang',
    startDate: '2026-02-01',
    endDate: '2027-01-31',
    rateExteriorWash: 65000,
    rateInteriorWash: 80000,
    rateCargoPackage: 0,
    rateCargoBulk: 0,
    status: 'active',
    notes: 'Khoán vệ sinh toa xe khách tuyến đón trả ga Ninh Hòa',
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'c-05',
    contractNumber: '05/2026/HĐGK-VTHN-NT',
    templateType: 'CARGO_DUAL_EMPLOYER',
    workerId: 'w-05',
    partyA: DEFAULT_PARTY_A,
    stationLocation: 'Ga Nha Trang (Bãi hàng)',
    signDate: '2026-02-05',
    signPlace: 'Chi nhánh Vận tải đường sắt Nha Trang',
    startDate: '2026-02-05',
    endDate: '2027-02-04',
    rateExteriorWash: 0,
    rateInteriorWash: 0,
    rateCargoPackage: 48000,
    rateCargoBulk: 36000,
    status: 'active',
    notes: 'Giao khoán bốc dỡ hàng nông sản & phân bón bãi hàng ga Nha Trang',
    createdAt: '2026-02-05T14:30:00Z',
  },
  {
    id: 'c-06',
    contractNumber: '06/2026/HĐNT-VTHN-NT',
    templateType: 'CARGO_PRINCIPLE_VTHN',
    workerId: 'w-06',
    partyA: DEFAULT_PARTY_A,
    stationLocation: 'Ga Nha Trang (Hóa vận)',
    signDate: '2026-02-10',
    signPlace: 'Chi nhánh Vận tải đường sắt Nha Trang',
    startDate: '2026-02-10',
    endDate: '2027-02-09',
    rateExteriorWash: 0,
    rateInteriorWash: 0,
    rateCargoPackage: 48000, // 48.000 đ/tấn
    rateCargoBulk: 38000,    // 38.000 đ/tấn
    status: 'active',
    notes: 'Hợp đồng nguyên tắc giao khoán dịch vụ bốc xếp theo nhu cầu thực tế tại Hóa vận Ga Nha Trang',
    createdAt: '2026-02-10T09:00:00Z',
  },
  {
    id: 'c-07',
    contractNumber: '07/2026/HĐGK-SP-NT',
    templateType: 'CLEANING_FREELANCE',
    workerId: 'w-07',
    partyA: DEFAULT_PARTY_A,
    stationLocation: 'Ga Tuy Hòa',
    signDate: '2026-02-15',
    signPlace: 'Chi nhánh Vận tải đường sắt Nha Trang',
    startDate: '2026-02-15',
    endDate: '2027-02-14',
    rateExteriorWash: 65000,
    rateInteriorWash: 80000,
    rateCargoPackage: 0,
    rateCargoBulk: 0,
    status: 'active',
    notes: 'Hợp đồng vệ sinh toa xe khách phục vụ đón trả tàu tại Trạm VTĐS Tuy Hòa',
    createdAt: '2026-02-15T09:15:00Z',
  },
  {
    id: 'c-08',
    contractNumber: '08/2026/HĐNT-VTHN-NT',
    templateType: 'CARGO_PRINCIPLE_VTHN',
    workerId: 'w-08',
    partyA: DEFAULT_PARTY_A,
    stationLocation: 'Ga Diêu Trì',
    signDate: '2026-02-20',
    signPlace: 'Chi nhánh Vận tải đường sắt Nha Trang',
    startDate: '2026-02-20',
    endDate: '2027-02-19',
    rateExteriorWash: 0,
    rateInteriorWash: 0,
    rateCargoPackage: 48000,
    rateCargoBulk: 38000,
    status: 'active',
    notes: 'Hợp đồng bốc xếp giải phóng hàng hóa toa xe tại Trạm VTĐS Diêu Trì',
    createdAt: '2026-02-20T09:30:00Z',
  },
];

export const INITIAL_ACCEPTANCE_REPORTS: AcceptanceReport[] = [
  {
    id: 'rep-01',
    reportNumber: 'BB-01/2026/NT',
    contractId: 'c-01',
    workerId: 'w-01',
    periodDescription: 'Đợt 1 tháng 01/2026',
    workStation: 'Ga Nha Trang',
    acceptanceDate: '2026-01-20',
    representativeA: 'Trần Văn Tám',
    roleA: 'Trực ban Ga Nha Trang',
    representativeB: 'Nguyễn Văn Hùng',
    items: [
      {
        id: 'item-101',
        workDate: '2026-01-15',
        wagonOrBatchNumber: 'B-31422, B-31425, A-31201',
        itemType: 'exterior',
        description: 'Xịt rửa vỏ ngoài toa xe khách đón trả tàu SE8',
        unit: 'toa xe',
        quantity: 12,
        unitPrice: 65000,
        amount: 780000,
        notes: 'Đã rửa sạch bùn đất',
      },
      {
        id: 'item-102',
        workDate: '2026-01-18',
        wagonOrBatchNumber: 'An-31502, B-31440',
        itemType: 'interior',
        description: 'Vệ sinh cọ rửa nội thất và kính cửa sổ toa xe',
        unit: 'toa xe',
        quantity: 8,
        unitPrice: 80000,
        amount: 640000,
        notes: 'Kính cửa sổ sáng rõ',
      },
    ],
    grossAmount: 1420000,
    isTaxWithheld: false, // Dưới 5 triệu -> 0% thuế TNCN
    taxRate: 0,
    taxAmount: 0,
    netAmount: 1420000,
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    paymentDate: '2026-01-22',
    paymentReference: 'UNC-VCB-098124',
    evaluationCompletedWagons: 20,
    qualityPassed: true,
    evaluationNotes: 'Khối lượng hoàn thành đúng kế hoạch dồn dịch; vỏ ngoài sạch bùn đất, rác thải thu gom đúng nơi quy định, kính cửa sáng rõ trước giờ chạy tàu.',
    createdAt: '2026-01-20T16:30:00Z',
  },
  {
    id: 'rep-02',
    reportNumber: 'BB-02/2026/NT',
    contractId: 'c-01',
    workerId: 'w-01',
    periodDescription: 'Tổng hợp Tháng 02/2026 (Phục vụ cao điểm Tết)',
    workStation: 'Ga Nha Trang',
    acceptanceDate: '2026-02-28',
    representativeA: 'Trần Văn Tám',
    roleA: 'Trực ban Ga Nha Trang',
    representativeB: 'Nguyễn Văn Hùng',
    items: [
      {
        id: 'item-201',
        workDate: '2026-02-10',
        wagonOrBatchNumber: 'Đoàn tàu tăng cường SNT2/4 (45 toa)',
        itemType: 'exterior',
        description: 'Rửa sạch vỏ ngoài toa xe khách đón trả khách Tết',
        unit: 'toa xe',
        quantity: 45,
        unitPrice: 65000,
        amount: 2925000,
        notes: 'Tàu đông khách, áp lực cao',
      },
      {
        id: 'item-202',
        workDate: '2026-02-20',
        wagonOrBatchNumber: 'Đoàn tàu SNT1/3 (30 toa)',
        itemType: 'interior',
        description: 'Tổng vệ sinh nội thất các toa xe giường nằm và ngồi mềm',
        unit: 'toa xe',
        quantity: 30,
        unitPrice: 80000,
        amount: 2400000,
        notes: 'Nội thất sạch sẽ đạt chuẩn',
      },
    ],
    grossAmount: 5325000,
    // Lao động vãng lai có cam kết thu nhập 08/CK-TNCN theo NĐ 253/2026/NĐ-CP -> Tạm thời chưa khấu trừ 10%
    isTaxWithheld: false,
    taxRate: 0,
    taxAmount: 0,
    netAmount: 5325000,
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    paymentDate: '2026-03-02',
    paymentReference: 'UNC-VCB-109432',
    evaluationCompletedWagons: 75,
    qualityPassed: true,
    evaluationNotes: 'Toàn bộ 75 toa xe được rửa sạch đạt chuẩn phục vụ đợt vận tải Tết Nguyên Đán; Bên B đã có Bản cam kết thu nhập 08/CK-TNCN còn hiệu lực nên tạm chưa khấu trừ 10%.',
    createdAt: '2026-02-28T17:00:00Z',
  },
  {
    id: 'rep-03',
    reportNumber: 'BB-03/2026/TC',
    contractId: 'c-02',
    workerId: 'w-02',
    periodDescription: 'Tổng hợp Tháng 02/2026',
    workStation: 'Ga Tháp Chàm',
    acceptanceDate: '2026-02-26',
    representativeA: 'Nguyễn Văn Hòa',
    roleA: 'Hóa vận Ga Tháp Chàm',
    representativeB: 'Trần Đình Dũng',
    items: [
      {
        id: 'item-301',
        workDate: '2026-02-12',
        wagonOrBatchNumber: 'Toa khách dừng đón ga Tháp Chàm',
        itemType: 'exterior',
        description: 'Xịt rửa vỏ ngoài toa xe khách vãng lai',
        unit: 'toa xe',
        quantity: 38,
        unitPrice: 65000,
        amount: 2470000,
      },
      {
        id: 'item-302',
        workDate: '2026-02-22',
        wagonOrBatchNumber: 'Toa xe kỹ thuật ga Tháp Chàm',
        itemType: 'interior',
        description: 'Vệ sinh nội thất toa xe theo tiêu chuẩn',
        unit: 'toa xe',
        quantity: 25,
        unitPrice: 80000,
        amount: 2000000,
      },
    ],
    grossAmount: 4470000,
    isTaxWithheld: false, // < 5.000.000đ -> 0% thuế
    taxRate: 0,
    taxAmount: 0,
    netAmount: 4470000,
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    paymentDate: '2026-03-01',
    paymentReference: 'UNC-BIDV-774120',
    evaluationCompletedWagons: 63,
    qualityPassed: true,
    evaluationNotes: 'Chất lượng vệ sinh bảo đảm đúng tiêu chuẩn kỹ thuật tác nghiệp ga; cá nhân thuộc diện hưu trí được miễn BHXH theo Điểm a Khoản 7 Điều 2 Luật BHXH 2024.',
    createdAt: '2026-02-26T15:00:00Z',
  },
  {
    id: 'rep-04',
    reportNumber: 'BB-04/2026/DK',
    contractId: 'c-03',
    workerId: 'w-03',
    periodDescription: 'Tháng 03/2026',
    workStation: 'Ga Diên Khánh',
    acceptanceDate: '2026-03-25',
    representativeA: 'Phạm Minh Trí',
    roleA: 'Phụ trách Hóa vận Ga Diên Khánh',
    representativeB: 'Lê Hoàng Nam',
    items: [
      {
        id: 'item-401',
        workDate: '2026-03-10',
        wagonOrBatchNumber: 'Đoàn tàu hàng G-1892 (8 toa hàng bao)',
        itemType: 'cargo_package',
        description: 'Bốc dỡ hàng bao bì xi măng từ toa xe sang xe tải',
        unit: 'tấn',
        quantity: 85,
        unitPrice: 45000,
        amount: 3825000,
        notes: 'Không rách vỡ bao',
      },
      {
        id: 'item-402',
        workDate: '2026-03-20',
        wagonOrBatchNumber: 'Đoàn tàu hàng G-2014 (Hàng rời)',
        itemType: 'cargo_bulk',
        description: 'Bốc xúc dỡ hàng rời nông sản sắn lát sang kho bãi ga',
        unit: 'tấn',
        quantity: 60,
        unitPrice: 35000,
        amount: 2100000,
        notes: 'Hàng không hao hụt',
      },
    ],
    grossAmount: 5925000,
    // Lao động đang đóng BHXH tại đơn vị thứ 1 -> có thu nhập 2 nơi -> Bắt buộc khấu trừ 10% khi >= 5 triệu theo NĐ 253/2026/NĐ-CP
    isTaxWithheld: true,
    taxRate: 0.1,
    taxAmount: 592500,
    netAmount: 5332500,
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    paymentDate: '2026-03-28',
    paymentReference: 'UNC-STB-992140',
    evaluationCompletedWagons: 145,
    qualityPassed: true,
    evaluationNotes: 'Khối lượng 145 tấn bốc dỡ hoàn thành đúng hạn; hàng hóa an toàn không thất thoát. Đã khấu trừ 10% thuế TNCN và Chi nhánh sẽ cấp Chứng từ khấu trừ thuế điện tử cho Bên B.',
    createdAt: '2026-03-25T16:00:00Z',
  },
  {
    id: 'rep-05',
    reportNumber: 'BB-05/2026/NT',
    contractId: 'c-05',
    workerId: 'w-05',
    periodDescription: 'Tháng 04/2026',
    workStation: 'Ga Nha Trang (Bãi hàng)',
    acceptanceDate: '2026-04-24',
    representativeA: 'Lê Thanh Bình',
    roleA: 'Trực ban Hóa vận Ga',
    representativeB: 'Đặng Quốc Tuấn',
    items: [
      {
        id: 'item-501',
        workDate: '2026-04-12',
        wagonOrBatchNumber: 'Toa hàng bốc dỡ phân bón',
        itemType: 'cargo_package',
        description: 'Bốc dỡ hàng bao kiện phân bón NPK từ toa xe sang xe đầu kéo',
        unit: 'tấn',
        quantity: 110,
        unitPrice: 48000,
        amount: 5280000,
      },
      {
        id: 'item-502',
        workDate: '2026-04-20',
        wagonOrBatchNumber: 'Toa hàng khoáng sản',
        itemType: 'cargo_bulk',
        description: 'Bốc dỡ hàng rời khoáng sản sang bãi hàng',
        unit: 'tấn',
        quantity: 50,
        unitPrice: 36000,
        amount: 1800000,
      },
    ],
    grossAmount: 7080000,
    isTaxWithheld: true,
    taxRate: 0.1,
    taxAmount: 708000,
    netAmount: 6372000,
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    paymentDate: '2026-04-28',
    paymentReference: 'UNC-VCB-882319',
    evaluationCompletedWagons: 160,
    qualityPassed: true,
    evaluationNotes: 'Hoàn thành bốc dỡ an toàn 160 tấn hàng; tuân thủ nghiêm ngặt quy tắc an toàn bãi hàng đường sắt. Khấu trừ 10% thuế TNCN số tiền 708.000đ.',
    createdAt: '2026-04-24T17:15:00Z',
  },
  {
    id: 'rep-06',
    reportNumber: 'BB-06/2026/NH',
    contractId: 'c-04',
    workerId: 'w-04',
    periodDescription: 'Tháng 05/2026',
    workStation: 'Ga Ninh Hòa',
    acceptanceDate: '2026-05-20',
    representativeA: 'Nguyễn Tấn Tài',
    roleA: 'Trực ban Ga Ninh Hòa',
    representativeB: 'Hoàng Thị Mai',
    items: [
      {
        id: 'item-601',
        workDate: '2026-05-15',
        wagonOrBatchNumber: 'Các toa xe đón trả tàu khách khu đoạn',
        itemType: 'exterior',
        description: 'Vệ sinh cọ rửa bề mặt ngoài toa xe',
        unit: 'toa xe',
        quantity: 40,
        unitPrice: 65000,
        amount: 2600000,
      },
      {
        id: 'item-602',
        workDate: '2026-05-18',
        wagonOrBatchNumber: 'Toa xe khách khu đoạn',
        itemType: 'interior',
        description: 'Vệ sinh nội thất toa xe khách',
        unit: 'toa xe',
        quantity: 20,
        unitPrice: 80000,
        amount: 1600000,
      },
    ],
    grossAmount: 4200000,
    isTaxWithheld: false, // Dưới 5 triệu -> 0%
    taxRate: 0,
    taxAmount: 0,
    netAmount: 4200000,
    paymentStatus: 'paid',
    paymentMethod: 'cash',
    paymentDate: '2026-05-22',
    paymentReference: 'PC-NH-052026',
    evaluationCompletedWagons: 60,
    qualityPassed: true,
    evaluationNotes: 'Khối lượng hoàn thành tốt, sạch sẽ; chi trả tiền mặt theo đề nghị của Bên B dưới ngưỡng 5.000.000 đồng.',
    createdAt: '2026-05-20T14:40:00Z',
  },
  {
    id: 'rep-07',
    reportNumber: 'BB-07/2026/NT',
    contractId: 'c-01',
    workerId: 'w-01',
    periodDescription: 'Đợt Tháng 06/2026 (Du lịch hè)',
    workStation: 'Ga Nha Trang',
    acceptanceDate: '2026-06-25',
    representativeA: 'Trần Văn Tám',
    roleA: 'Trực ban Ga Nha Trang',
    representativeB: 'Nguyễn Văn Hùng',
    items: [
      {
        id: 'item-701',
        workDate: '2026-06-15',
        wagonOrBatchNumber: 'Đoàn tàu du lịch hè',
        itemType: 'exterior',
        description: 'Xịt rửa vỏ ngoài toa xe khách đón trả khách du lịch',
        unit: 'toa xe',
        quantity: 50,
        unitPrice: 65000,
        amount: 3250000,
      },
      {
        id: 'item-702',
        workDate: '2026-06-22',
        wagonOrBatchNumber: 'Toa xe du lịch hè SNT',
        itemType: 'interior',
        description: 'Vệ sinh nội thất và kính bề mặt toa xe',
        unit: 'toa xe',
        quantity: 35,
        unitPrice: 80000,
        amount: 2800000,
      },
    ],
    grossAmount: 6050000,
    isTaxWithheld: false, // Đã nộp Bản cam kết thu nhập 08/CK-TNCN
    taxRate: 0,
    taxAmount: 0,
    netAmount: 6050000,
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    paymentDate: '2026-06-29',
    paymentReference: 'UNC-VCB-290611',
    evaluationCompletedWagons: 85,
    qualityPassed: true,
    evaluationNotes: 'Chất lượng vệ sinh bảo đảm tiêu chuẩn kỹ thuật đón khách mùa cao điểm hè; Bên B đã cam kết chỉ có duy nhất nguồn thu vãng lai tại Chi nhánh chưa tới ngưỡng chịu thuế năm.',
    createdAt: '2026-06-25T17:30:00Z',
  },
  {
    id: 'rep-08',
    reportNumber: 'BB-08/2026/DK',
    contractId: 'c-03',
    workerId: 'w-03',
    periodDescription: 'Tháng 07/2026',
    workStation: 'Ga Diên Khánh',
    acceptanceDate: '2026-07-28',
    representativeA: 'Phạm Minh Trí',
    roleA: 'Phụ trách Hóa vận Ga Diên Khánh',
    representativeB: 'Lê Hoàng Nam',
    items: [
      {
        id: 'item-801',
        workDate: '2026-07-14',
        wagonOrBatchNumber: 'Đoàn tàu hàng xi măng',
        itemType: 'cargo_package',
        description: 'Bốc dỡ hàng bao kiện',
        unit: 'tấn',
        quantity: 90,
        unitPrice: 45000,
        amount: 4050000,
      },
      {
        id: 'item-802',
        workDate: '2026-07-24',
        wagonOrBatchNumber: 'Đoàn tàu hàng sắn lát nông sản',
        itemType: 'cargo_bulk',
        description: 'Bốc dỡ hàng rời',
        unit: 'tấn',
        quantity: 50,
        unitPrice: 35000,
        amount: 1750000,
      },
    ],
    grossAmount: 5800000,
    isTaxWithheld: true,
    taxRate: 0.1,
    taxAmount: 580000,
    netAmount: 5220000,
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    paymentDate: '2026-07-31',
    paymentReference: 'UNC-STB-112034',
    evaluationCompletedWagons: 140,
    qualityPassed: true,
    evaluationNotes: 'Khối lượng nghiệm thu đạt 140 tấn; tuân thủ an toàn đường ray tuyệt đối. Khấu trừ 10% thuế TNCN số tiền 580.000đ.',
    createdAt: '2026-07-28T16:20:00Z',
  },
  {
    id: 'rep-09',
    reportNumber: 'BB-09/2026/NT',
    contractId: 'c-01',
    workerId: 'w-01',
    periodDescription: 'Đợt gần nhất (Tháng 09/2026)',
    workStation: 'Ga Nha Trang',
    acceptanceDate: '2026-09-18',
    representativeA: 'Trần Văn Tám',
    roleA: 'Trực ban Ga Nha Trang',
    representativeB: 'Nguyễn Văn Hùng',
    items: [
      {
        id: 'item-901',
        workDate: '2026-09-12',
        wagonOrBatchNumber: 'Toa xe khách đón trả tàu SE6/SE8',
        itemType: 'exterior',
        description: 'Rửa sạch vỏ ngoài toa xe khách đón trả',
        unit: 'toa xe',
        quantity: 26,
        unitPrice: 65000,
        amount: 1690000,
      },
      {
        id: 'item-902',
        workDate: '2026-09-16',
        wagonOrBatchNumber: 'Toa xe đón trả khách SNT',
        itemType: 'interior',
        description: 'Vệ sinh nội thất toa xe khách',
        unit: 'toa xe',
        quantity: 18,
        unitPrice: 80000,
        amount: 1440000,
      },
    ],
    grossAmount: 3130000,
    isTaxWithheld: false,
    taxRate: 0,
    taxAmount: 0,
    netAmount: 3130000,
    paymentStatus: 'approved', // Đã duyệt chi, đang chuyển khoản
    paymentMethod: 'bank_transfer',
    evaluationCompletedWagons: 44,
    qualityPassed: true,
    evaluationNotes: 'Đạt chuẩn kỹ thuật vệ sinh toa xe phục vụ chạy tàu; trình Giám đốc chi nhánh duyệt chi trả.',
    createdAt: '2026-09-18T15:00:00Z',
  },
  {
    id: 'rep-10',
    reportNumber: 'BB-10/2026/HV-NT',
    contractId: 'c-06',
    workerId: 'w-06',
    periodDescription: 'Đợt Tháng 08/2026 (Giải phóng toa hàng)',
    workStation: 'Ga Nha Trang (Hóa vận)',
    acceptanceDate: '2026-08-25',
    representativeA: 'Võ Minh Tuấn',
    roleA: 'Trực ban Hóa vận Ga',
    representativeB: 'Phạm Văn Túc',
    items: [
      {
        id: 'item-1001',
        workDate: '2026-08-14',
        wagonOrBatchNumber: 'Đoàn tàu hàng G-1950 (Toa H-22104, H-22108)',
        itemType: 'cargo_package',
        description: 'Bốc dỡ hàng bao kiện phân bón từ toa xe sang xe ô tô tải',
        unit: 'tấn',
        quantity: 65,
        unitPrice: 48000,
        amount: 3120000,
        notes: 'Bảo quản nguyên vẹn hàng hóa không rách vỡ',
      },
      {
        id: 'item-1002',
        workDate: '2026-08-20',
        wagonOrBatchNumber: 'Toa xe hàng rời G-33012',
        itemType: 'cargo_bulk',
        description: 'Bốc dỡ, chuyển tải hàng rời từ toa xe vào kho ga hóa vận',
        unit: 'tấn',
        quantity: 70,
        unitPrice: 38000,
        amount: 2660000,
        notes: 'Giải phóng toa xe đúng thời gian quy định',
      },
    ],
    grossAmount: 5780000,
    // Bên B là đối tượng hưu trí, có Bản cam kết thu nhập 08/CK-TNCN theo NĐ 253/2026/NĐ-CP -> Tạm thời chưa khấu trừ
    isTaxWithheld: false,
    taxRate: 0,
    taxAmount: 0,
    netAmount: 5780000,
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    paymentDate: '2026-08-28',
    paymentReference: 'UNC-VCB-771290',
    evaluationCompletedWagons: 135,
    qualityPassed: true,
    evaluationNotes: 'Khối lượng bốc dỡ: Đúng số lượng theo vận đơn toa xe. Chất lượng: Hàng hóa nguyên vẹn, giải phóng toa xe đúng thời gian quy định. Hai bên thống nhất làm thủ tục thanh toán số tiền trên cho Bên nhận khoán.',
    createdAt: '2026-08-25T16:00:00Z',
  },
  {
    id: 'rep-07',
    reportNumber: 'BB-07/2026/TH',
    contractId: 'c-07',
    workerId: 'w-07',
    periodDescription: 'Đợt ngày 25/08/2026',
    workStation: 'Ga Tuy Hòa',
    acceptanceDate: '2026-08-25',
    representativeA: 'Nguyễn Văn Tâm',
    roleA: 'Trực ban Ga Tuy Hòa',
    representativeB: 'Nguyễn Thành Long',
    items: [
      {
        id: 'item-2001',
        workDate: '2026-08-22',
        wagonOrBatchNumber: 'Đoàn tàu SE22 (Toa 11421, 11425)',
        itemType: 'exterior',
        description: 'Xịt rửa sạch vỏ ngoài và cọ rửa kính cửa sổ toa xe khách',
        unit: 'toa xe',
        quantity: 2,
        unitPrice: 65000,
        amount: 130000,
        notes: 'Toa xe sạch bùn đất',
      },
      {
        id: 'item-2002',
        workDate: '2026-08-24',
        wagonOrBatchNumber: 'Đoàn tàu SE4 (Toa 11502, 11508)',
        itemType: 'interior',
        description: 'Vệ sinh nội thất toa xe khách',
        unit: 'toa xe',
        quantity: 2,
        unitPrice: 80000,
        amount: 160000,
        notes: 'Thu gom rác và lau dọn sàn sạch sẽ',
      },
    ],
    grossAmount: 290000,
    isTaxWithheld: false,
    taxRate: 0,
    taxAmount: 0,
    netAmount: 290000,
    paymentStatus: 'pending',
    paymentMethod: 'cash',
    evaluationCompletedWagons: 4,
    qualityPassed: true,
    evaluationNotes: 'Trạm VTĐS Tuy Hòa nghiệm thu: 04 toa xe khách được rửa sạch vỏ ngoài và nội thất, đạt tiêu chuẩn kỹ thuật tác nghiệp ga tàu.',
    createdAt: '2026-08-25T17:00:00Z',
  },
  {
    id: 'rep-08',
    reportNumber: 'BB-08/2026/DT',
    contractId: 'c-08',
    workerId: 'w-08',
    periodDescription: 'Đợt ngày 28/08/2026',
    workStation: 'Ga Diêu Trì',
    acceptanceDate: '2026-08-28',
    representativeA: 'Lê Văn Hiền',
    roleA: 'Trực ban Hóa vận Ga Diêu Trì',
    representativeB: 'Bùi Văn Phước',
    items: [
      {
        id: 'item-3001',
        workDate: '2026-08-26',
        wagonOrBatchNumber: 'Đoàn tàu hàng SH-2 (Toa H-44120)',
        itemType: 'cargo_package',
        description: 'Bốc dỡ xi măng bao kiện từ toa xe sang xe tải',
        unit: 'tấn',
        quantity: 50,
        unitPrice: 48000,
        amount: 2400000,
        notes: 'Không rách bao bì, đủ khối lượng',
      },
      {
        id: 'item-3002',
        workDate: '2026-08-27',
        wagonOrBatchNumber: 'Toa xe hàng G-55201',
        itemType: 'cargo_bulk',
        description: 'Bốc dỡ nông sản hàng rời vào kho ga',
        unit: 'tấn',
        quantity: 60,
        unitPrice: 38000,
        amount: 2280000,
        notes: 'Giải phóng toa xe an toàn',
      },
    ],
    grossAmount: 468000,
    isTaxWithheld: false,
    taxRate: 0,
    taxAmount: 0,
    netAmount: 468000,
    paymentStatus: 'pending',
    paymentMethod: 'bank_transfer',
    evaluationCompletedWagons: 110,
    qualityPassed: true,
    evaluationNotes: 'Trạm VTĐS Diêu Trì nghiệm thu: Bốc dỡ an toàn 110 tấn hàng hóa, không hao hụt rơi vãi, giải phóng toa xe kịp thời gian dồn dịch.',
    createdAt: '2026-08-28T10:00:00Z',
  }
];
